services:
  mongodb:
     image: mongo:7.0
     container_name: chat_mongodb
     ports:
      - "27017:27017"
     restart: unless-stopped
     environment:
      - MONGODB_URI=${MONGODB_URI}
     volumes:
       - mongodb_data:/data/db
     networks:
       - chat_network 
  
  postgres:
      image: postgres:bookworm
      container_name: postgres-chat-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=chat_app_test
      networks:
        - chat_network
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
    

  chat-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_1
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      # - REDIS_URI=${REDIS_URI}
    networks:
      - chat_network
    ports:
      - "3001:3000"
    expose:
      - "3001:3000"
    depends_on:
      - mongodb
      # - redis

  chat-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_2
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      # - REDIS_URI=${REDIS_URI}
    networks:
      - chat_network
    ports:
      - "3002:3000"
    expose:
      - "3000"
    depends_on:
      - mongodb
      # - redis

  chat-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_3
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      # - REDIS_URI=${REDIS_URI}
    networks:
      - chat_network
    ports:
      - "3003:3000"
    expose:
      - "3000"
    depends_on:
      - mongodb
      # - redis
      
  # redis:
  #   container-name: redis:8.2-rc1
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - chat_network

  nginx:
    image: nginx:alpine
    container_name: chat_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-app-1
      - chat-app-2
      - chat-app-3
    networks:
      - chat_network
volumes:
  mongodb_data:
  postgres_data:

networks:
  chat_network:
    driver: bridge